// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FileProcessor is an autogenerated mock type for the FileProcessor type
type FileProcessor struct {
	mock.Mock
}

// Start provides a mock function with given fields: ctx
func (_m *FileProcessor) Start(ctx context.Context) {
	_m.Called(ctx)
}

// NewFileProcessor creates a new instance of FileProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileProcessor {
	mock := &FileProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
