// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FinishFileProcesssor is an autogenerated mock type for the FinishFileProcesssor type
type FinishFileProcesssor struct {
	mock.Mock
}

// Start provides a mock function with given fields: ctx
func (_m *FinishFileProcesssor) Start(ctx context.Context) {
	_m.Called(ctx)
}

// NewFinishFileProcesssor creates a new instance of FinishFileProcesssor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinishFileProcesssor(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinishFileProcesssor {
	mock := &FinishFileProcesssor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
