// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StatusUpdater is an autogenerated mock type for the StatusUpdater type
type StatusUpdater struct {
	mock.Mock
}

// Watch provides a mock function with given fields:
func (_m *StatusUpdater) Watch() {
	_m.Called()
}

// NewStatusUpdater creates a new instance of StatusUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusUpdater {
	mock := &StatusUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
