// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TransactionProcesssor is an autogenerated mock type for the TransactionProcesssor type
type TransactionProcesssor struct {
	mock.Mock
}

// Start provides a mock function with given fields: ctx
func (_m *TransactionProcesssor) Start(ctx context.Context) {
	_m.Called(ctx)
}

// NewTransactionProcesssor creates a new instance of TransactionProcesssor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionProcesssor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionProcesssor {
	mock := &TransactionProcesssor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
